let questionnarieItems = [
  { "left": "irritante", "right": "divertido" },
  { "left": "incompreensivel", "right": "compreensível" },
  { "left": "criativo", "right": "entediante" },
  { "left": "fácil de aprender", "right": "difícil de aprender" },
  { "left": "valioso", "right": "insignificante" },
  { "left": "chato", "right": "emocionante" },
  { "left": "desinteressante", "right": "interessante" },
  { "left": "imprevisível", "right": "previsível" },
  { "left": "rápido", "right": "lento" },
  { "left": "inovador", "right": "convencional" },
  { "left": "obstrutivo", "right": "facilitador" },
  { "left": "bom", "right": "mau" },
  { "left": "complicado", "right": "fácil" },
  { "left": "detestável", "right": "agradável" },
  { "left": "comum", "right": "vanguardista" },
  { "left": "desconfortável", "right": "confortável" },
  { "left": "seguro", "right": "inseguro" },
  { "left": "motivante", "right": "desmotivante" },
  { "left": "atende as expectativas", "right": "não atende as expectativas" },
  { "left": "ineficiente", "right": "eficiente" },
  { "left": "claro", "right": "confuso" },
  { "left": "não prático", "right": "prático" },
  { "left": "organizado", "right": "desorganizado" },
  { "left": "atraente", "right": "repulsivo" },
  { "left": "amigável", "right": "não amigável" },
  { "left": "conservador", "right": "inovador" }
];
